---
  TRADE_OPTIONS:
    QUANTITY: 1
    PAIRING: USDT
    RUN_EVERY: 0.1
    TEST: True
    SL: 3
    TP: 3
    ENABLE_TSL: True
    TSL: 1
    TTP: 1
    UC: 20
    ROTATE_IP: False
    MULTIPLIER: 100
    AVG_SIZE: 10
