---
  TRADE_OPTIONS:
    # In your pairing coin
    QUANTITY: 1
    # BTCUSDT will be bought for example
    PAIRING: USDT
    # How often to check for posts and run the script
    # in minutes
    RUN_EVERY: 0.1
    TEST: True
    SL: 3
    TP: 3
    ENABLE_TSL: True
    TSL: 1
    TTP: 1
    UC: 20
